/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_FitVerse (void);
GtkWidget* create_TIEC (void);
GtkWidget* create_GCS (void);
GtkWidget* create_Administrateur (void);
GtkWidget* create_Membre (void);
