/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gstdio.h>

#include "interface.h"
#include "support.h"

/* Déclarations des callbacks de TIEC */
void on_button14_clicked(GtkButton *, gpointer);
void on_button15_clicked(GtkButton *, gpointer);
void on_button16_clicked(GtkButton *, gpointer);
void on_spinbutton1_value_changed(GtkSpinButton *, gpointer);
void on_spinbutton4_value_changed(GtkSpinButton *, gpointer);
void on_spinbutton5_value_changed(GtkSpinButton *, gpointer);
void on_spinbutton6_value_changed(GtkSpinButton *, gpointer);
void on_radiobutton3_toggled(GtkToggleButton *, gpointer);
void on_radiobutton4_toggled(GtkToggleButton *, gpointer);
void on_radiobutton5_toggled(GtkToggleButton *, gpointer);

int
main (int argc, char *argv[])
{
  GtkWidget *FitVerse;
  GtkWidget *TIEC;
  GtkWidget *GCS;          /* <-- ajout */

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /* Ajouter le répertoire pixmaps local pour le développement */
  gchar *cwd = g_get_current_dir ();
  gchar *pixmaps_path = g_build_filename (cwd, "pixmaps", NULL);
  if (g_file_test (pixmaps_path, G_FILE_TEST_IS_DIR)) {
    add_pixmap_directory (pixmaps_path);
  }
  g_free (pixmaps_path);
  
  add_pixmap_directory ("pixmaps");
  add_pixmap_directory ("../pixmaps");
  add_pixmap_directory ("./pixmaps");
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  g_free (cwd);

  /* ===== CRÉATION & AFFICHAGE DES 3 FENÊTRES ===== */

  /* 1) GCS (fenêtre de choix Admin / Membre) */
  fprintf(stderr, "[DEBUG] Création de GCS\n");
  GCS = create_GCS();
  gtk_widget_show_all(GCS);

  /* 2) FitVerse (gestion des cours) */
  fprintf(stderr, "[DEBUG] Création de FitVerse\n");
  FitVerse = create_FitVerse();
  gtk_widget_show_all(FitVerse);

  /* 3) TIEC (inscription membre) */
  fprintf(stderr, "[DEBUG] Création de TIEC\n");
  TIEC = create_TIEC();
  gtk_widget_show_all(TIEC);

  /* ===== Branchement des signaux TIEC ===== */
  g_signal_connect(lookup_widget(TIEC, "button14"), "clicked", G_CALLBACK(on_button14_clicked), NULL);
  g_signal_connect(lookup_widget(TIEC, "button15"), "clicked", G_CALLBACK(on_button15_clicked), NULL);
  g_signal_connect(lookup_widget(TIEC, "button16"), "clicked", G_CALLBACK(on_button16_clicked), NULL);

  g_signal_connect(lookup_widget(TIEC, "spinbutton1"), "value_changed", G_CALLBACK(on_spinbutton1_value_changed), NULL);
  g_signal_connect(lookup_widget(TIEC, "spinbutton4"), "value_changed", G_CALLBACK(on_spinbutton4_value_changed), NULL);
  g_signal_connect(lookup_widget(TIEC, "spinbutton5"), "value_changed", G_CALLBACK(on_spinbutton5_value_changed), NULL);
  g_signal_connect(lookup_widget(TIEC, "spinbutton6"), "value_changed", G_CALLBACK(on_spinbutton6_value_changed), NULL);

  g_signal_connect(lookup_widget(TIEC, "radiobutton3"), "toggled", G_CALLBACK(on_radiobutton3_toggled), NULL);
  g_signal_connect(lookup_widget(TIEC, "radiobutton4"), "toggled", G_CALLBACK(on_radiobutton4_toggled), NULL);
  g_signal_connect(lookup_widget(TIEC, "radiobutton5"), "toggled", G_CALLBACK(on_radiobutton5_toggled), NULL);

  fprintf(stderr, "[DEBUG] Démarrage de la boucle principale GTK\n");
  gtk_main ();
  fprintf(stderr, "[DEBUG] Fin de l'application\n");
  return 0;
}

