/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout (void);
GtkWidget* create_reservation (void);
GtkWidget* create_modification (void);
GtkWidget* create_recherche (void);
GtkWidget* create_FitVerse (void);
GtkWidget* create_TIEC (void);
GtkWidget* create_window_gestion_evenement (void);
GtkWidget* create_window_ajouter_evenement (void);
GtkWidget* create_window_modifier_evenement (void);
GtkWidget* create_windowsinscireevent (void);
GtkWidget* create_acceuil_mohamed (void);
GtkWidget* create_ajouter_un_entraineur_mohamed (void);
GtkWidget* create_modifer_un_entraineur_mohamed (void);
GtkWidget* create_supprimer_un_entraineur_mohamed (void);
GtkWidget* create_inscrire____un_cours_sportif_mohamed (void);
GtkWidget* create_login_entraineur_mohamed (void);
GtkWidget* create_login_mohamed (void);
GtkWidget* create_login_admin_mohamed (void);
GtkWidget* create_window1 (void);
