/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_interface_admin (void);
GtkWidget* create_log_in_ADMIN (void);
GtkWidget* create_Demande_d_un_entraineur_priv__ (void);
GtkWidget* create_LOGIN_MEMBRE (void);
GtkWidget* create_login (void);
GtkWidget* create_Demandes_envoy__es (void);
