/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h" 

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

/*int main (int argc, char *argv[])
{
  GtkWidget *FitVerse;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  // Création de la fenêtre principale
  FitVerse = create_FitVerse ();
  gtk_widget_show (FitVerse);

  // Récupérer le GtkCombo
  GtkWidget *combo = lookup_widget(FitVerse, "GCIA_comboType");

  //  Connecter le signal "changed" sur GtkEntry (saisie manuelle)
  GtkEntry *entry = GTK_ENTRY(GTK_COMBO(combo)->entry);
  g_signal_connect(G_OBJECT(entry), "changed",
                   G_CALLBACK(on_GCIA_comboType_entry_changed),
                   NULL);

  //  Connecter le signal "select-child" sur GtkList (choix dans la liste)
  GtkList *list = GTK_LIST(GTK_COMBO(combo)->list);
  //  On passe l’entry comme user_data pour éviter l’erreur list->parent
  g_signal_connect(G_OBJECT(list), "select-child",
                   G_CALLBACK(on_GCIA_comboType_list_selected),
                   entry);

  gtk_main ();
  return 0;
}*/
int main (int argc, char *argv[])
{
  GtkWidget *FitVerse;
  GtkWidget *TIEC;  
  GtkWidget *Ajout;
  GtkWidget *Reservation;
  GtkWidget *Chercher;
  GtkWidget *window_gestion_evenement;
  GtkWidget *windowsinscireevent ;
  GtkWidget *login_window;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif
  gtk_set_locale ();
  gtk_init (&argc, &argv);
  
  
  add_pixmap_directory ("pixmaps");
  
  
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  

//SARRA
  Ajout = create_ajout ();
  gtk_widget_show (Ajout);

  
  Reservation = create_reservation ();
  gtk_widget_show (Reservation);

  Chercher = create_recherche();
  gtk_widget_show (Chercher);




  gtk_main ();
  return 0;
}


